### ISSUE TITLE
What about HTTPS support?

### ISSUE THREAD

**Issue by cs16lover** [pichi-router/pichi#1]
From documentation I saw that it doesn't have HTTPS proxy support (engress).

Will you add HTTPS support?

**Comment by cs16lover** [comment]
Very good. 

Is there a road map for the project?
When will version 1.2 be released?

**Comment by pichi-router** [comment]
[Commit ba8c766](https://github.com/pichi-router/pichi/commit/ba8c7661093054441e9a3e9332d507b5d5f5d72d) implements TLS support for HTTP/SOCKS5 adapters.
