### ISSUE TITLE
User/pass auth with socks5

### ISSUE THREAD

**Issue by a0s** [pichi-router/pichi#4]
Hi! Could you pls provide some example to authenticate several different user/password for socks5 proxy? Could it be possible with pichi ?

**Comment by pichi-router** [comment]
Yes, Pichi has already provided the basic authentication for HTTP/Socks5 adapters from [1.3.0-rc](https://github.com/pichi-router/pichi/releases/tag/1.3.0-rc). If you want to setup a socks5 server with the basic authentication, please send some JSON data like:

```
{
  "type": "socks5",
  "bind": "::",
  "port": 1080,
  "credentials": {
    "username0": "password0",
    "username1": "password1",
    "username2": "password2"
  }
}
```
to /ingresses/socks5-with-auth. On the other hand, the JSON data for socks5 client is similar to

```
{
  "type": "socks5",
  "host": "socks5.host.name",
  "port": 1080,
  "credential": ["username", "password"]
}
``` 
They are also accepted if you insert them into the initial JSON file with `--json` option.

So, please follow the [Pichi API document](https://app.swaggerhub.com/apis/pichi-router/pichi-api/1.3) to get the details of the JSON format, and I'll update README file to add the examples you mentioned.

And furthermore, TLS might be probably used if the authentication is enabled. But there's a bug might cause TLS adapters not working. I think it will be fixed when releasing 1.3.1.
